package cr.ac.una.prograiv.taxi.domain;
// Generated 06-oct-2017 13:10:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private Date ano;
     private String modelo;
     private char color;
     private boolean estado;
     private Set<Conductor> conductors = new HashSet<Conductor>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String placa, Date ano, String modelo, char color, boolean estado) {
        this.placa = placa;
        this.ano = ano;
        this.modelo = modelo;
        this.color = color;
        this.estado = estado;
    }
    public Vehiculo(String placa, Date ano, String modelo, char color, boolean estado, Set<Conductor> conductors) {
       this.placa = placa;
       this.ano = ano;
       this.modelo = modelo;
       this.color = color;
       this.estado = estado;
       this.conductors = conductors;
    }
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public char getColor() {
        return this.color;
    }
    
    public void setColor(char color) {
        this.color = color;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Conductor> getConductors() {
        return this.conductors;
    }
    
    public void setConductors(Set<Conductor> conductors) {
        this.conductors = conductors;
    }




}


